### ISSUE TITLE
error: struct.error: unpack requires a buffer of 271 bytes

### ISSUE THREAD

**Issue by vtmocanu** [OxMohsen/uniquify-bot#2]
I get:
```
python3 main.py
[04-Jan-23 10:09:06 - INFO] - bot - Bot DKiller (@CORECT_NAME_OF_bot) started!
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    Bot().run()
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/utilities/run.py", line 80, in run
    run(self.start())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/storage_local/dkiller_bot/bot.py", line 35, in start
    self.USER, self.USER_ID = await User().start()
  File "/storage_local/dkiller_bot/user.py", line 23, in start
    await super().start()
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/utilities/start.py", line 58, in start
    is_authorized = await self.connect()
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/auth/connect.py", line 40, in connect
    await self.load_session()
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/client.py", line 596, in load_session
    await self.storage.open()
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/storage/memory_storage.py", line 59, in open
    dc_id, api_id, test_mode, auth_key, user_id, is_bot = struct.unpack(
struct.error: unpack requires a buffer of 271 bytes
```
in my config.py i have:
```
class Config(object):
    # Get a bot token from @botfather
    TG_BOT_TOKEN = os.environ.get("TG_BOT_TOKEN", "5...46:AAEE....RQ")

    # Get from my.telegram.org
    APP_ID = int(os.environ.get("APP_ID", "2....4"))

    # Get from my.telegram.org
    API_HASH = os.environ.get("API_HASH", "d....18b")

    # Authorized users to use this bot
    AUTH_USERS = set(int(x) for x in os.environ.get("AUTH_USERS", "5....5").split())

    # session name
    TG_USER_SESSION_NAME = os.environ.get("TG_USER_SESSION_NAME", "oxmohsen")

    # tg user session string
    TG_USER_SESSION_STRING = os.environ.get("TG_USER_SESSION_STRING", "1BJ....Ckk=")
```

I've redacted the actual values.
Do you have any ideeas what could be wrong?
I've created the bot from another user, not the one under which I'm running the APP ID and HASH, but it should not matter i think as long i have the Bot Token.
Thank you!

**Comment by OxMohsen** [comment]
hi
i think your TG_USER_SESSION_STRING have some issue try login with phone number.

**Comment by vtmocanu** [comment]
How do i do that? I should put the phone number under TG_BOT_TOKEN ? Or leave TG_BOT_TOKEN empty and it will ask me for the phone?
Thanks!

Later edit: tried both ways and it did not work.

**Comment by OxMohsen** [comment]
like this
```python
class Config(object):
    TG_BOT_TOKEN = "your bot token"
    APP_ID = 123456
    API_HASH = "your api hash"
    AUTH_USERS = {987654321, 123456789}
    TG_USER_SESSION_NAME = "JustAName"
    TG_USER_SESSION_STRING = ""
```
when you run the bot, it will ask you your phone number and code

**Comment by vtmocanu** [comment]
You were correct, now it works, thank you!
